apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/knowlesy/argo-home.git
      revision: HEAD
      files:
      - path: "apps-config/*.json"
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      sources:
      # 1. Define Private Repo Reference
      - repoURL: https://github.com/knowlesy/argo-private.git
        targetRevision: HEAD
        ref: private-repo

      # 2. Define Public Repo Reference (NEW)
      - repoURL: https://github.com/knowlesy/argo-home.git
        targetRevision: HEAD
        ref: public-repo

      # 3. The Chart & Value Files
      - repoURL: '{{chartRepo}}'
        chart: '{{chartName}}'
        targetRevision: '{{chartVersion}}'
        helm:
          releaseName: '{{appName}}'
          valueFiles:
          # A. Load Public Config First
          - '$public-repo/apps-values/{{appName}}/values.yaml'

          # B. Load Private Config Second (Overrides public if keys match)
          - '$private-repo/configs/{{appName}}/values.yaml'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{targetNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
