apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd # Changed from 'platform' to 'argocd'
spec:
  project: default
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: 2.22.0
    helm:
      releaseName: pihole
      # The pipe | below is crucial. It tells YAML this is a string block.
      values: |
        serviceWeb:
          type: LoadBalancer
        adminPassword: "admin"
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Create// filepath: /Users/peterknowles/Repo/argo-home/apps/pihole.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd # Changed from 'platform' to 'argocd'
spec:
  project: default
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: 2.22.0
    helm:
      releaseName: pihole
      # The pipe | below is crucial. It tells YAML this is a string block.
      values: |
        serviceWeb:
          type: LoadBalancer
        adminPassword: "admin"
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Create